name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: ipaulo/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            Dwarf Therapist.tex

